apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: appdynamics-daemonset
  labels:
    app: appdynamics-daemonset
    version: v1
spec:
  template:
    metadata:
      labels:
        name: appdynamics-daemonset
        app: appdynamics-daemonset
        version: v1
    spec:
      containers:
      - name: hostname
        image: store/appdynamics/machine:4.5
        env:
        - name: 