apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myValue: "Hello World"
  drink: {{ .Values.favoriteDrink | upper | repeat 5 | quote }}
  salad: {{ .Values.global.salad }}

  
