apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: appdynamics-daemonset
  labels:
    app: appdynamics-daemonset
    version: v1
spec:
  template:
    metadata:
      labels:
        name: appdynamics-daemonset
        app: appdynamics-daemonset
        version: v1
    spec:
      containers:
      - name: appdynamics-daemonset
        image: store/appdynamics/machine:4.5
        volumeMounts:
          - mountPath: /app-agent
            name: app-agent
          - mountPath: /var/run/docker.sock
            name: docker
        env:
          - name: APPDYNAMICS_CONTROLLER_HOST_NAME
            value: "lee201811072338099.saas.appdynamics.com"
          - name: APPDYNAMICS_CONTROLLER_PORT
            value: "443"
          - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
            value: "true"
          - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
            value: "lee201811072338099"
          - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
            value: "cdcd8jxi2ieh"
          - name: "APPDYNAMICS_AGENT_UNIQUE_HOST_ID"
            value: "host-20181115"
          - name: MACHINE_AGENT_PROPERTIES
            value: "-Dappdynamics.sim.enabled=true -Dappdynamics.docker.enabled=true"
      volumes:
        - name: app-agent
          hostPath:
            path: /opt/app-agent
        - name: docker
          hostPath:
            path: /var/run/docker.sock